### ekf config file ###
/odom_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    publish_acceleration: true
    publish_tf: true
    # use_control: true
    # stamped_control: true
    # control_timeout: 0.1
    # control_config: [true, true, true, true, true, true]

    map_frame: map # Defaults to "map" if unspecified
    odom_frame: odom # Defaults to "odom" if unspecified
    base_link_frame: base_link # Defaults to "base_link" ifunspecified
    world_frame: odom # Defaults to the value ofodom_frame if unspecified

    odom0: /controller/odometry
    odom0_config:
      [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
      ]

    imu0: /x3_mecanum/imu
    imu0_remove_gravitational_acceleration: true
    imu0_config:
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
      ]
